//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidoriBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResponse
    {
        public int ResponseID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Contents { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Reply { get; set; }
    
        public virtual User User { get; set; }
    }
}
